var error = false;
var exception;
var f1 = false;

try {
    var i = 10 / 0;
} catch (e) {
    exception = e;
    error = true;
} finally {
    f1 = true;
}
